// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsfRyw2iwgAG_J0MUAlxtk3evG80sshMg',
    appId: '1:629275070223:web:3f0c4cb892ec780036387a',
    messagingSenderId: '629275070223',
    projectId: 'smart-edu-app-c82d8',
    authDomain: 'smart-edu-app-c82d8.firebaseapp.com',
    storageBucket: 'smart-edu-app-c82d8.firebasestorage.app',
    measurementId: 'G-NXFHBN011W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBktMsgl9ZX2VVgVIoIAzYipSjhWQm1o7s',
    appId: '1:629275070223:android:654f94db1f10ed2f36387a',
    messagingSenderId: '629275070223',
    projectId: 'smart-edu-app-c82d8',
    storageBucket: 'smart-edu-app-c82d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKA0ar7T-ilTHQrjJbtgT_soDgSzPOMek',
    appId: '1:629275070223:ios:6c58db3c66374c8d36387a',
    messagingSenderId: '629275070223',
    projectId: 'smart-edu-app-c82d8',
    storageBucket: 'smart-edu-app-c82d8.firebasestorage.app',
    iosClientId: '629275070223-vdipojoluupc5uqipu2t0bjclm9qvls7.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartEduApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKA0ar7T-ilTHQrjJbtgT_soDgSzPOMek',
    appId: '1:629275070223:ios:6c58db3c66374c8d36387a',
    messagingSenderId: '629275070223',
    projectId: 'smart-edu-app-c82d8',
    storageBucket: 'smart-edu-app-c82d8.firebasestorage.app',
    iosClientId: '629275070223-vdipojoluupc5uqipu2t0bjclm9qvls7.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartEduApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsfRyw2iwgAG_J0MUAlxtk3evG80sshMg',
    appId: '1:629275070223:web:c905d25c9c976a2636387a',
    messagingSenderId: '629275070223',
    projectId: 'smart-edu-app-c82d8',
    authDomain: 'smart-edu-app-c82d8.firebaseapp.com',
    storageBucket: 'smart-edu-app-c82d8.firebasestorage.app',
    measurementId: 'G-J7W61DD4FV',
  );
}
